In [9]:
# series using read_csv
import pandas as pd
df=pd.read_csv("../datasets/bollywood.csv")

In [10]:
df.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [11]:
df.head(10)

                                  movie                  lead
0              Uri: The Surgical Strike         Vicky Kaushal
1                         Battalion 609           Vicky Ahuja
2  The Accidental Prime Minister (film)           Anupam Kher
3                       Why Cheat India         Emraan Hashmi
4                       Evening Shadows      Mona Ambegaonkar
5                           Soni (film)  Geetika Vidya Ohlyan
6                         Fraud Saiyaan          Arshad Warsi
7                            Bombairiya          Radhika Apte
8      Manikarnika: The Queen of Jhansi        Kangana Ranaut
9                      Thackeray (film)   Nawazuddin Siddiqui