In [9]:
# series using read_csv
import pandas as pd
df=pd.read_csv("../datasets/bollywood.csv")

In [10]:
df.head()

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

In [11]:
df.head(10)

                                  movie                  lead
0              Uri: The Surgical Strike         Vicky Kaushal
1                         Battalion 609           Vicky Ahuja
2  The Accidental Prime Minister (film)           Anupam Kher
3                       Why Cheat India         Emraan Hashmi
4                       Evening Shadows      Mona Ambegaonkar
5                           Soni (film)  Geetika Vidya Ohlyan
6                         Fraud Saiyaan          Arshad Warsi
7                            Bombairiya          Radhika Apte
8      Manikarnika: The Queen of Jhansi        Kangana Ranaut
9                      Thackeray (film)   Nawazuddin Siddiqui

In [12]:
# with one col
pd.read_csv("../datasets/subs.csv")

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [13]:
# but this data is not a series.
type(pd.read_csv("../datasets/subs.csv"))

pandas.DataFrame

In [ ]:
# so we use squeeze() for convert into series from dataframe.
df = pd.read_csv("../datasets/subs.csv")
series = df.squeeze()
print(series)
print(type(series))   # pandas mid data ko truncate kr de ta hai automatically.

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64
<class 'pandas.Series'>

In [19]:
# with two column
df = pd.read_csv("../datasets/kohli_ipl.csv")
series = df["runs"]
print(series)
print(type(series))

0       1
1      23
2      13
3      12
4       1
       ..
210     0
211    20
212    73
213    25
214     7
Name: runs, Length: 215, dtype: int64
<class 'pandas.Series'>

In [ ]:
df = pd.read_csv("../datasets/kohli_ipl.csv",index_col="match_no")
series = df["runs"]     # so we use runs for the 2 columns.
print(series)
print(type(series))

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64
<class 'pandas.Series'>

In [23]:
df = pd.read_csv("../datasets/bollywood.csv",index_col="movie")
print(df.columns)

Index(['lead'], dtype='str')

In [ ]:
df = pd.read_csv("../datasets/bollywood.csv",index_col="movie")
series = df.iloc[:, 0]
print(series)
print(type(series))
# always us column ka name, name bane ga jo values me ho ga.

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str
<class 'pandas.Series'>